A measurement is a central concept in quantum mechanics. An easy way to think about it as a sample from a probability distribution: it is a random variable with a number of outcomes, each outcome is produced with a certain probability. 

Measurement connect the quantum world to our classical one: we cannot directly observe the quantum state in nature, we can only gather statistics about it with measurements. It sounds like a harsh boundary between a quantum and a classical system that can only be bridged by measurement. The reality is more subtle: unless a quantum system is perfectly isolated, it interacts with its surrounding environment. This leads to introduction of mixed states, which in one limit recover classical probabilities.


# More on the bra-ket notation

Before we take a deep dive into what measurements are, we need to introduce one more notation to complement the ket: it called a bra and it is denoted by $\langle\psi|$ for some quantum state $|\psi\rangle$. Together they form the bra-ket or Dirac notation. A bra is the conjugate transpose of a ket, and the other way around. This also means that a bra is a row vector. For instance, this is the bra for $|0\rangle$

In [19]:
import numpy as np
zero_ket = np.array([[1], [0]])
print("|0> ket:\n", zero_ket)
print("<0| bra:\n", zero_ket.T.conj())

|0> ket:
 [[1]
 [0]]
<0| bra:
 [[1 0]]


In [20]:
zero_ket

array([[1],
       [0]])

In [21]:
print("|0> ket:\n", zero_ket)

|0> ket:
 [[1]
 [0]]


In [22]:
print("<0| bra:\n", zero_ket.T.conj())

<0| bra:
 [[1 0]]


In [23]:
zero_ket.T.conj()

array([[1, 0]])

In [24]:
zero_ket.T.conj()

array([[1, 0]])

In [25]:
zero_ket.T.conj() @ zero_ket

array([[1]])

In [26]:
one_ket = np.array([[0], [1]])

In [27]:
one_ket

array([[0],
       [1]])

In [29]:
zero_ket.T.conj() 

array([[1, 0]])

In [30]:
one_ket

array([[0],
       [1]])

In [31]:
zero_ket.T.conj() @ one_ket

array([[0]])

!