In [1]:
import numpy as np

a = [0,1,2,3,4,5,6,7,8]

In [2]:
len(a)

9

In [3]:
x = np.reshape(a, (3, 3))

In [4]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
x[:, :2]

array([[0, 1],
       [3, 4],
       [6, 7]])

In [9]:
x.sum()

36

In [10]:
x.mean()

4.0

In [11]:
x.max()

8

In [12]:
x.min()

0

In [13]:
x.std()

2.581988897471611

In [48]:
x.var()

6.666666666666667

In [67]:
a0, a1, aa = x.sum(axis=0), x.sum(axis=0), x.sum()
a0, a1, aa

(array([ 9, 12, 15]), array([ 9, 12, 15]), 36)

In [71]:
a0.tolist(), a1.tolist(), aa

([9, 12, 15], [9, 12, 15], 36)

In [88]:
m0, m1, ma = x.mean(axis=0), x.mean(axis=1), x.mean()
mean = [m0.tolist(), m1.tolist(), ma]
mean

[[3.0, 4.0, 5.0], [1.0, 4.0, 7.0], 4.0]

In [89]:
v0, v1, va = x.var(axis=0), x.var(axis=1), x.var()
variance = [v0.tolist(), v1.tolist(), va]
variance

[[6.0, 6.0, 6.0],
 [0.6666666666666666, 0.6666666666666666, 0.6666666666666666],
 6.666666666666667]

In [90]:
std0, std1, stda = x.std(axis=0), x.std(axis=1), x.std()
std = [std0.tolist(), std1.tolist(), stda]
std

[[2.449489742783178, 2.449489742783178, 2.449489742783178],
 [0.816496580927726, 0.816496580927726, 0.816496580927726],
 2.581988897471611]

In [100]:
max0, max1, maxa = x.max(axis=0), x.max(axis=1), x.max()
maximum= [max0.tolist(), max1.tolist(), maxa]
maximum

[[6, 7, 8], [2, 5, 8], 8]

In [102]:
min0, min1, mina = x.min(axis=0), x.min(axis=1), x.min()
minimum = [min0.tolist(), min1.tolist(), mina]
minimum

[[0, 1, 2], [0, 3, 6], 0]

In [103]:
sum0, sum1, suma = x.sum(axis=0), x.sum(axis=1), x.sum()
summation = [sum0.tolist(), sum1.tolist(), suma]
summation

[[9, 12, 15], [3, 12, 21], 36]

In [104]:
expected = {'mean':mean, 
            'variance':variance, 
            'standard deviation':std, 
           'max': maximum,
           'min': minimum,
           'sum': summation}

In [105]:
expected

{'mean': [[3.0, 4.0, 5.0], [1.0, 4.0, 7.0], 4.0],
 'variance': [[6.0, 6.0, 6.0],
  [0.6666666666666666, 0.6666666666666666, 0.6666666666666666],
  6.666666666666667],
 'standard deviation': [[2.449489742783178,
   2.449489742783178,
   2.449489742783178],
  [0.816496580927726, 0.816496580927726, 0.816496580927726],
  2.581988897471611],
 'max': [[6, 7, 8], [2, 5, 8], 8],
 'min': [[0, 1, 2], [0, 3, 6], 0],
 'sum': [[9, 12, 15], [3, 12, 21], 36]}

In [40]:
array to list

SyntaxError: invalid syntax (<ipython-input-40-e0e7c5cc3df3>, line 1)